@startuml

title __OCAJAVA's Class Diagram__\n

  namespace If {
    class If.Quartalsermittlung {
    }
  }
  

  namespace If {
    class If.Switch {
    }
  }
  

  namespace If {
    class If.ifTeil1 {
    }
  }
  

  namespace If {
    class If.ifTeil2 {
    }
  }
  

  namespace If {
    class If.ifTeil2c {
    }
  }
  

  namespace If {
    class If.ifTeil3 {
    }
  }
  

  namespace array {
    class array.ArraySortSuchen {
    }
  }
  

  namespace array {
    class array.ArrrayTeoria {
    }
  }
  

  namespace array {
    namespace Aufgabe {
      class array.Aufgabe.AufgabeArrayT1AB {
      }
    }
  }
  

  namespace array {
    namespace Aufgabe {
      class array.Aufgabe.AufgabeArrayT1C {
      }
    }
  }
  

  namespace array {
    namespace Aufgabe {
      class array.Aufgabe.AufgabeArrayT2AB {
      }
    }
  }
  

  namespace array {
    namespace Aufgabe {
      class array.Aufgabe.AufgabeArrayT2C {
      }
    }
  }
  

  namespace array {
    namespace Aufgabe {
      class array.Aufgabe.AufgabeArrayT3 {
      }
    }
  }
  

  namespace array {
    namespace Aufgabe {
      class array.Aufgabe.AufgabeArrayT3Reverse {
      }
    }
  }
  

  namespace array {
    namespace Aufgabe {
      class array.Aufgabe.AufgabeArrayT4 {
      }
    }
  }
  

  namespace array {
    namespace Aufgabe {
      class array.Aufgabe.AusgabeArrayT5 {
      }
    }
  }
  

  namespace array {
    class array.MehrereDimensionen {
    }
  }
  

  namespace array {
    namespace ist {
      class arrayList.ArrayListTeoria {
      }
    }
  }
  

  namespace array {
    namespace ist {
      class arrayList.AufgabeArrayList1 {
      }
    }
  }
  

  namespace array {
    namespace ist {
      class arrayList.AufgabeArrayList2 {
      }
    }
  }
  

  namespace array {
    namespace ist {
      class arrayList.Tier {
      }
    }
  }
  

  namespace captainCiaoCiao {
    class captainCiaoCiao.Circle {
    }
  }
  

  namespace doWhile {
    class doWhile.AufgabeDoWhile {
    }
  }
  

  namespace fechas {
    class fechas.Aufgabe2 {
    }
  }
  

  namespace fechas {
    class fechas.Aufgabe3 {
    }
  }
  

  namespace fechas {
    class fechas.Aufgabe4 {
    }
  }
  

  namespace fechas {
    namespace Aufgabe5 {
      class fechas.Aufgabe5.Feiertag {
      }
    }
  }
  

  namespace fechas {
    namespace Aufgabe5 {
      class fechas.Aufgabe5.Main {
      }
    }
  }
  

  namespace fechas {
    class fechas.fechas {
    }
  }
  

  namespace forSchleifen {
    class forSchleifen.Quersumme {
    }
  }
  

  namespace forSchleifen {
    class forSchleifen.Sterne {
    }
  }
  

  namespace forSchleifen {
    class forSchleifen.Test {
    }
  }
  

  namespace forSchleifen {
    class forSchleifen.exercisesABCDEF {
    }
  }
  

  namespace forSchleifen {
    class forSchleifen.randomE {
    }
  }
  

  namespace klassen.ubung1 {
    class klassen.ubung1.Main {
    }
  }
  

  namespace klassen.ubung1 {
    class klassen.ubung1.Produkt {
    }
  }
  

  namespace mull {
    class mull.EVA {
    }
  }
  

  namespace mull {
    class mull.Objetos {
    }
  }
  

  namespace mull {
    class mull.dummy {
    }
  }
  

  namespace stringBuilder {
    class stringBuilder.AufgabeStringBuilder {
    }
  }
  

  namespace stringBuilder {
    class stringBuilder.AufgabeStringBuilder2 {
    }
  }
  

  namespace stringClass {
    class stringClass.AufgabeString {
    }
  }
  

  namespace stringClass {
    class stringClass.AufgabeWortRaten {
    }
  }
  

  namespace stringClass {
    class stringClass.StringTeoria {
    }
  }
  

  namespace whilewhile {
    class whilewhile.AufgabeWhile {
    }
  }
  

  namespace whilewhile {
    class whilewhile.exerciseA {
    }
  }
  

  namespace whilewhile {
    class whilewhile.whileExeciseD {
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
